In [1]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [2]:
import numpy as np
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2) # Матричное умножение
print(result)


[[19 22]
 [43 50]]


In [3]:
import numpy as np
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data) # Среднее значение
std_dev = np.std(data) 
print(std_dev)

1.4142135623730951


In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4])
result = arr * 2
print(result)

[2 4 6 8]


In [5]:
import numpy as np
v_vert_np = np.array([[1], [2]])
print(v_vert_np)

[[1]
 [2]]


In [6]:
import numpy as np
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


In [7]:
import numpy as np
A = np.matrix('1. -3.; 2. 5.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)

[[ 1. -3.]
 [ 2.  5.]]
