## Лабораторная работа №2
### Вариант 26

In [6]:
import numpy as np

Задание 1. **Создание и изменение массивов**

Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. Выведите итоговый массив.

In [25]:
mass = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(f'Исходный массив\n{mass}')

mass *= 2
mass[mass > 10] = 0

print(f'Итоговый массив:\n{mass}')

Исходный массив
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Итоговый массив:
[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


Задание 2. **Работа с булевыми масками**

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Затем замените их на -1 и выведите обновленный массив.

In [6]:
mass = np.random.randint(1, 101, size = 20)
print(f'Исходный массив: {mass}')

multipleOf5 = mass % 5 == 0
mass[mass % 5 == 0] = -1
print(f'Итоговый массив: {mass}')
mass[multipleOf5]
print(f'Делятся на 5 без остатка: {mass}')



Исходный массив: [ 77  27  22  47 100  81  43  42  39  78  40  26  90  66  88  50   4  33
  89  39]
Итоговый массив: [77 27 22 47 -1 81 43 42 39 78 -1 26 -1 66 88 -1  4 33 89 39]
Делятся на 5 без остатка: [77 27 22 47 -1 81 43 42 39 78 -1 26 -1 66 88 -1  4 33 89 39]


Задание 3. **Объединение и разбиение массивов**

Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50.

- Объедините эти массивы в один двумерный массив (по строкам).
- Разделите полученный массив на два массива, каждый из которых содержит 5 элементов.

In [9]:
mass1 = np.random.randint(0, 51, size=(1,5))
mass2 = np.random.randint(0, 51, size=(1,5))

mass3 = np.vstack((mass1,mass2))
mass4 = np.split(mass3, 2, axis=0)

print(f'Первый массив:\n{mass1}\nВторой массив:\n{mass2}')
print(f'Объединенный массив:\n{mass3}\nРазделенный массив:\n{mass4}')

Первый массив:
[[44 23 15 43 24]]
Второй массив:
[[13 45 36 29 31]]
Объединенный массив:
[[44 23 15 43 24]
 [13 45 36 29 31]]
Разделенный массив:
[array([[44, 23, 15, 43, 24]]), array([[13, 45, 36, 29, 31]])]


Задание 4. **Генерация и работа с линейными последовательностями.**

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10. Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. Выведите результаты.

In [12]:
massFirst = np.arange(-10, 10, 0.4)
mass = np.round(mass,1)
print(f'Исходный массив:\n {mass}')

sumOfAll = mass.sum()
sumOfNegative = mass[mass<0].sum()
sumOfPositive = mass[mass>0].sum()

print(f'Сумма всех элементов: {sumOfAll}')
print(f'Сумма всех отрицательных: {sumOfNegative}')
print(f'Сумма всех положительных: {sumOfPositive}')

Исходный массив:
 [77 27 22 47 -1 81 43 42 39 78 -1 26 -1 66 88 -1  4 33 89 39]
Сумма всех элементов: 797
Сумма всех отрицательных: -4
Сумма всех положительных: 801


Задание 5. Работа с диагональными и единичными матрицами

Создайте:

- Единичную матрицу размером 4х4.
- Диагональную матрицу размером 4×4 с диагональными элементами \[5, 10, 15, 20] (не использовать циклы).

Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [15]:
identMatr = np.eye(4)
diagMatr = np.matrix('5, 0, 0, 0; 0, 10, 0, 0; 0, 0, 15, 0; 10, 0, 0, 20')

identSum = identMatr.sum()
diagSum = diagMatr.sum()

print(f'Единичная матрица:\n{identMatr}')
print(f'Диагональная матрица:\n{diagMatr}')
print(f'Сумма единичной: {identSum}\nСумма диагональной: {diagSum}')
if identSum > diagSum:
    print('Сумма единичной матрицы больше')
else:
    print('Сумма диагональной матрицы больше')

Единичная матрица:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Диагональная матрица:
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [10  0  0 20]]
Сумма единичной: 4.0
Сумма диагональной: 60
Сумма диагональной матрицы больше


Задание 6. Создание и базовые операции с матрицами

Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите:

- Их сумму
- Их разность
- Их поэлементное произведение.

In [18]:
mass1 = np.random.randint(1, 20, size = (3,3))
mass2 = np.random.randint(1, 20, size = (3,3))


sumMatr = mass1 + mass2
diffMatr = mass1 - mass2
dotElementMatr = mass1 * mass2

print(f'Исходный массив 1:\n{mass1}')
print(f'Исходный массив 2:\n{mass2}')
print(f'Сумма матриц:\n{sumMatr}')
print(f'Разность матриц:\n{diffMatr}')
print(f'Поэлементное произведение матриц:\n{dotElementMatr}')

Исходный массив 1:
[[19  6 10]
 [ 3  3 15]
 [11 17  1]]
Исходный массив 2:
[[ 6 12 11]
 [ 5 16 13]
 [11 13 16]]
Сумма матриц:
[[25 18 21]
 [ 8 19 28]
 [22 30 17]]
Разность матриц:
[[ 13  -6  -1]
 [ -2 -13   2]
 [  0   4 -15]]
Поэлементное произведение матриц:
[[114  72 110]
 [ 15  48 195]
 [121 221  16]]


Задание 7. **Умножение матриц**

Создайте две матрицы NumPy:

- Первую размером 2×3, заполненную случайными числами от 1 до 10.
- Вторую размером 3×2, заполненную случайными числами от 1 до 10.

In [29]:
mass1 = np.random.randint(1,11, size = (2,3))
mass2 = np.random.randint(1,11, size = (3,2))
proizMatr = np.dot(mass1,mass2)

print(f'Исходный массив 1:\n {mass1}')
print(f'Исходный массив 2:\n {mass2}')
print(f'Произведение матриц:\n {proizMatr}')

Исходный массив 1:
 [[9 8 8]
 [1 4 8]]
Исходный массив 2:
 [[7 4]
 [3 3]
 [1 9]]
Произведение матриц:
 [[ 95 132]
 [ 27  88]]


Задание 8. **Определитель и обратная матрица**

Создайте случайную квадратную матрицу 3х3. Найдите и выведите:

- Определитель этой матрицы
- Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена)

In [74]:
mass = np.random.randint(-10,10, size = (3,3))
det = round(np.linalg.det(mass))

print(f'Исходный массив:\n {mass}')
print(f'Определитель равен: {det}')
if det == 0:
    print('Обратную матрицу нельзя найти, т.к. определитель равен 0')
else:
    invMatr = np.linalg.inv(mass)
    print(f'Обратная матрица:\n{invMatr}')


Исходный массив:
 [[ -9  -8  -9]
 [ -2   5   3]
 [  9 -10  -8]]
Определитель равен: 227
Обратная матрица:
[[-0.04405286  0.11453744  0.09251101]
 [ 0.04845815  0.67400881  0.19823789]
 [-0.11013216 -0.71365639 -0.26872247]]


Задание 9. Транспонирование и след матрицы

Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите:

- Исходную матрицу
- Транспонированную матрицу
- След матрицы (сумму элементов по главной диагонали)

In [65]:
mass = np.random.randint(-10,10, size = (4,4))
transpMatr = np.transpose(mass)
diagMatr = np.diag(mass)
sledMatr = np.sum(diagMatr)

print(f'Исходный массив:\n{mass}')
print(f'Транспонированная матрица:\n{transpMatr}')
print(f'След матрицы:{sledMatr}')

Исходный массив:
[[-10   0  -6   3]
 [  3  -3  -7   2]
 [ -8   2   1  -5]
 [ -3   0  -3  -9]]
Транспонированная матрица:
[[-10   3  -8  -3]
 [  0  -3   2   0]
 [ -6  -7   1  -3]
 [  3   2  -5  -9]]
След матрицы:-21


Задарние 10. **Системы линейных уравнений**

Решите систему линейных уравнений вида: 

2x + 3y - z = 5

4x - y + 2z = 6

-3x + 5y + 4z = -2

Используйте матричное представление Ax = B , где A – матрица коэффициентов, x – вектор неизвестных, B – вектор правой части. Решите систему с помощью np.linalg.solve и выведите результат.

In [80]:
mass = np.array([[2, 3, -1], [4, -1, 2], [-3, 5, 4]])
b = np.array([5, 6, -2])
x = np.linalg.solve(mass, b)

print('Ответ:')
print(f'x = {round(x[0],3)}')
print(f'y = {round(x[1],3)}')
print(f'z = {round(x[2],3)}')

Ответ:
x = 1.64
y = 0.577
z = 0.009


Задание 11. **Индивидуальное задание**

Решите индивидуальное задание согласно варианта. Каждое задание предусматривает построение системы линейных уравнений. Решите полученную систему уравнений с использованием библиотеки NumPy. Для решения системы используйте метод Крамера и матричный метод. Сравните полученные результаты, с результатами, полученными с помощью np.linalg.solve.

**Смешивание сплавов**. Для создания нового металлического сплава используются три вида металлов. Первый содержит 40% железа, второй — 60%, третий — 80%. Нужно получить 200 кг сплава с 65% железа, при этом второго металла должно быть в два раза больше, чем первого. Сколько килограммов каждого металла нужно взять?

Система уравнений:

`x + y + z = 200`

`0.4x + 0.6y + 0.8z = 130`

`-2x + y + 0z = 0`

In [51]:
a = np.array([[1, 1, 1], [0.4, 0.6, 0.8], [-2, 1, 0]])
b = np.array([200, 130, 0])

det_A = np.linalg.det(a)

A_x = a.copy()
A_x[:, 0] = b 
A_y = a.copy()
A_y[:, 1] = b
A_z = a.copy()
A_z[:, 2] = b

det_Ax = np.linalg.det(A_x)
det_Ay = np.linalg.det(A_y)
det_Az = np.linalg.det(A_z)

x = det_Ax / det_A
y = det_Ay / det_A
z = det_Az / det_A

x, y, z = np.round([x, y, z], 1)

print('Метод Крамера:')
print(f'x = {x}, y = {y}, z = {z}')

Метод Крамера:
x = 37.5, y = 75.0, z = 87.5


In [59]:
a = np.array([[1, 1, 1], [0.4, 0.6, 0.8], [-2, 1, 0]])
b = np.array([200, 130, 0])

A_inv = np.linalg.inv(a)

v = np.dot(A_inv, b)

x, y, z = np.round(v, 1)

print('Матричный метод:')
print(f'x = {x}, y = {y}, z = {z}')

Матричный метод:
x = 37.5, y = 75.0, z = 87.5


In [61]:
a = np.array([[1, 1, 1], [0.4, 0.6, 0.8], [-2, 1, 0]])
b = np.array([200, 130, 0])
v = np.round(np.linalg.solve(a, b), 2)

x = v[0]
y = v[1]
z = v[2]

print('Решение с помощью linalg:')
print(f'x = {x}, y = {y}, z = {z}')

Решение с помощью linalg:
x = 37.5, y = 75.0, z = 87.5
