## Лабораторная работа №2
### Вариант 26

In [33]:
import numpy as np

Задание 1. **Создание и изменение массивов**

Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. Выведите итоговый массив.

In [36]:
mass = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(f'Исходный массив\n{mass}')

mass *= 2
mass[mass > 10] = 0

print(f'Итоговый массив:\n{mass}')

Исходный массив
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Итоговый массив:
[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


Задание 2. **Работа с булевыми масками**

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Затем замените их на -1 и выведите обновленный массив.

In [75]:
mass = np.random.randint(1, 101, size = 20)
print(f'Исходный массив: {mass}')

multipleOf5 = mass.copy()
multipleOf5[multipleOf5 % 5 != 0] = 0;
mass[mass % 5 == 0] = -1
print(f'Делятся на 5 без остатка: {multipleOf5}')
print(f'Итоговый массив: {mass}')

Исходный массив: [20 59 41 95 58 45 58  3 72 29 26 53 47 31 26 79 55 85 59 85]
Делятся на 5 без остатка: [20  0  0 95  0 45  0  0  0  0  0  0  0  0  0  0 55 85  0 85]
Итоговый массив: [-1 59 41 -1 58 -1 58  3 72 29 26 53 47 31 26 79 -1 -1 59 -1]


Задание 3. **Объединение и разбиение массивов**

Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50.

- Объедините эти массивы в один двумерный массив (по строкам).
- Разделите полученный массив на два массива, каждый из которых содержит 5 элементов.

In [42]:
mass1 = np.random.randint(0, 51, size=(1,5))
mass2 = np.random.randint(0, 51, size=(1,5))

mass3 = np.vstack((mass1,mass2))
mass4 = np.split(mass3, 2, axis=0)

print(f'Первый массив:\n{mass1}\nВторой массив:\n{mass2}')
print(f'Объединенный массив:\n{mass3}\nРазделенный массив:\n{mass4}')

Первый массив:
[[20 12 25  0 18]]
Второй массив:
[[19 25 12 26  1]]
Объединенный массив:
[[20 12 25  0 18]
 [19 25 12 26  1]]
Разделенный массив:
[array([[20, 12, 25,  0, 18]]), array([[19, 25, 12, 26,  1]])]


Задание 4. **Генерация и работа с линейными последовательностями.**

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10. Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. Выведите результаты.

In [45]:
low = -10
high = 10
n = 50

mass = np.random.uniform(low, high, n)

mass = np.round(mass, 2)

print(mass)

sumOfAll = mass.sum()
sumOfNegative = mass[mass<0].sum()
sumOfPositive = mass[mass>0].sum()

print(f'Сумма всех элементов: {sumOfAll}')
print(f'Сумма всех отрицательных: {sumOfNegative}')
print(f'Сумма всех положительных: {sumOfPositive}')

[ 0.09  8.57 -4.6   7.96 -8.74  3.48 -1.84  8.21 -6.74 -4.67 -4.55  2.16
  3.43  4.66  2.48  7.34 -6.21 -6.66 -0.46 -8.04 -0.03  9.23  1.26  0.37
  3.96  0.69  3.4   6.57  4.14  9.06 -2.31 -3.74  6.89 -0.92 -4.54 -3.65
 -3.5  -5.35  7.77  0.69  7.33 -0.6   8.95  9.58 -8.02  1.16  7.71  4.09
 -5.27  5.28]
Сумма всех элементов: 56.07000000000001
Сумма всех отрицательных: -90.43999999999998
Сумма всех положительных: 146.51000000000002


Задание 5. Работа с диагональными и единичными матрицами

Создайте:

- Единичную матрицу размером 4х4.
- Диагональную матрицу размером 4×4 с диагональными элементами \[5, 10, 15, 20] (не использовать циклы).

Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [48]:
identMatr = np.eye(4)
diagMatr = np.matrix('5, 0, 0, 0; 0, 10, 0, 0; 0, 0, 15, 0; 10, 0, 0, 20')

identSum = identMatr.sum()
diagSum = diagMatr.sum()

print(f'Единичная матрица:\n{identMatr}')
print(f'Диагональная матрица:\n{diagMatr}')
print(f'Сумма единичной: {identSum}\nСумма диагональной: {diagSum}')
if identSum > diagSum:
    print('Сумма единичной матрицы больше')
else:
    print('Сумма диагональной матрицы больше')

Единичная матрица:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Диагональная матрица:
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [10  0  0 20]]
Сумма единичной: 4.0
Сумма диагональной: 60
Сумма диагональной матрицы больше


Задание 6. Создание и базовые операции с матрицами

Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите:

- Их сумму
- Их разность
- Их поэлементное произведение.

In [51]:
mass1 = np.random.randint(1, 20, size = (3,3))
mass2 = np.random.randint(1, 20, size = (3,3))


sumMatr = mass1 + mass2
diffMatr = mass1 - mass2
dotElementMatr = mass1 * mass2

print(f'Исходный массив 1:\n{mass1}')
print(f'Исходный массив 2:\n{mass2}')
print(f'Сумма матриц:\n{sumMatr}')
print(f'Разность матриц:\n{diffMatr}')
print(f'Поэлементное произведение матриц:\n{dotElementMatr}')

Исходный массив 1:
[[19 18 12]
 [13  9 11]
 [ 6 10 13]]
Исходный массив 2:
[[ 9  3  1]
 [ 5  2 17]
 [18  3 18]]
Сумма матриц:
[[28 21 13]
 [18 11 28]
 [24 13 31]]
Разность матриц:
[[ 10  15  11]
 [  8   7  -6]
 [-12   7  -5]]
Поэлементное произведение матриц:
[[171  54  12]
 [ 65  18 187]
 [108  30 234]]


Задание 7. **Умножение матриц**

Создайте две матрицы NumPy:

- Первую размером 2×3, заполненную случайными числами от 1 до 10.
- Вторую размером 3×2, заполненную случайными числами от 1 до 10.

In [54]:
mass1 = np.random.randint(1,11, size = (2,3))
mass2 = np.random.randint(1,11, size = (3,2))
proizMatr = np.dot(mass1,mass2)

print(f'Исходный массив 1:\n {mass1}')
print(f'Исходный массив 2:\n {mass2}')
print(f'Произведение матриц:\n {proizMatr}')

Исходный массив 1:
 [[ 6  6  7]
 [ 5  9 10]]
Исходный массив 2:
 [[8 9]
 [5 5]
 [3 1]]
Произведение матриц:
 [[ 99  91]
 [115 100]]


Задание 8. **Определитель и обратная матрица**

Создайте случайную квадратную матрицу 3х3. Найдите и выведите:

- Определитель этой матрицы
- Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена)

In [57]:
mass = np.random.randint(-10,10, size = (3,3))
det = round(np.linalg.det(mass))

print(f'Исходный массив:\n {mass}')
print(f'Определитель равен: {det}')
if det == 0:
    print('Обратную матрицу нельзя найти, т.к. определитель равен 0')
else:
    invMatr = np.linalg.inv(mass)
    print(f'Обратная матрица:\n{invMatr}')


Исходный массив:
 [[-6 -7 -7]
 [-4  2 -6]
 [ 9 -4 -9]]
Определитель равен: 896
Обратная матрица:
[[-0.046875   -0.0390625   0.0625    ]
 [-0.10044643  0.13058036 -0.00892857]
 [-0.00223214 -0.09709821 -0.04464286]]


Задание 9. Транспонирование и след матрицы

Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите:

- Исходную матрицу
- Транспонированную матрицу
- След матрицы (сумму элементов по главной диагонали)

In [60]:
mass = np.random.randint(-10,10, size = (4,4))
transpMatr = np.transpose(mass)
diagMatr = np.diag(mass)
sledMatr = np.sum(diagMatr)

print(f'Исходный массив:\n{mass}')
print(f'Транспонированная матрица:\n{transpMatr}')
print(f'След матрицы:{sledMatr}')

Исходный массив:
[[-8 -7 -1 -8]
 [-8  8  5  0]
 [ 7 -2 -4 -9]
 [-1  1  4 -9]]
Транспонированная матрица:
[[-8 -8  7 -1]
 [-7  8 -2  1]
 [-1  5 -4  4]
 [-8  0 -9 -9]]
След матрицы:-13


Задание 10. **Индивидуальное задание**

Решите индивидуальное задание согласно варианта. Каждое задание предусматривает построение системы линейных уравнений. Решите полученную систему уравнений с использованием библиотеки NumPy. Для решения системы используйте метод Крамера и матричный метод. Сравните полученные результаты, с результатами, полученными с помощью np.linalg.solve.

**Смешивание сплавов**. Для создания нового металлического сплава используются три вида металлов. Первый содержит 40% железа, второй — 60%, третий — 80%. Нужно получить 200 кг сплава с 65% железа, при этом второго металла должно быть в два раза больше, чем первого. Сколько килограммов каждого металла нужно взять?

Система уравнений:

`x + y + z = 200`

`0.4x + 0.6y + 0.8z = 130`

`-2x + y + 0z = 0`

In [63]:
a = np.array([[1, 1, 1], [0.4, 0.6, 0.8], [-2, 1, 0]])
b = np.array([200, 130, 0])

det_A = np.linalg.det(a)

A_x = a.copy()
A_x[:, 0] = b 
A_y = a.copy()
A_y[:, 1] = b
A_z = a.copy()
A_z[:, 2] = b

det_Ax = np.linalg.det(A_x)
det_Ay = np.linalg.det(A_y)
det_Az = np.linalg.det(A_z)

x = det_Ax / det_A
y = det_Ay / det_A
z = det_Az / det_A

x, y, z = np.round([x, y, z], 1)

print('Метод Крамера:')
print(f'x = {x}, y = {y}, z = {z}')

Метод Крамера:
x = 37.5, y = 75.0, z = 87.5


In [65]:
a = np.array([[1, 1, 1], [0.4, 0.6, 0.8], [-2, 1, 0]])
b = np.array([200, 130, 0])

A_inv = np.linalg.inv(a)

v = np.dot(A_inv, b)

x, y, z = np.round(v, 1)

print('Матричный метод:')
print(f'x = {x}, y = {y}, z = {z}')

Матричный метод:
x = 37.5, y = 75.0, z = 87.5


In [67]:
a = np.array([[1, 1, 1], [0.4, 0.6, 0.8], [-2, 1, 0]])
b = np.array([200, 130, 0])
v = np.round(np.linalg.solve(a, b), 2)

x = v[0]
y = v[1]
z = v[2]

print('Решение с помощью linalg:')
print(f'x = {x}, y = {y}, z = {z}')

Решение с помощью linalg:
x = 37.5, y = 75.0, z = 87.5
